# Terraform release pipeline
variables:
  - group: Digital Platform POC - Azure
  - group: Digital Platform POC - General
  - name: 'known_host'
    value: 'ssh.dev.azure.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H'
  - name: tf_state_filename
    value: 'azure-${{ parameters.Project }}-${{ parameters.Environment }}.terraform.tfstate'
  - name: tf_directory
    value: '$(System.DefaultWorkingDirectory)/terraform/azure'

parameters:
  - name: Agency
    displayName: Agency Name
    type: string
    default: DORIS
  - name: Environment
    displayName: Environment
    type: string
    default: dev
    values:
    - dev
    - tst
    - stg
    - prd
  - name: Application
    displayName: Application description
    type: string
    default: THELMA POC
  - name: Project
    displayName: Project Name
    type: string
    default: THELMA
  - name: UsedBy
    displayName: Used By
    type: string
    default: DORIS App Dev
  - name: SupportedBy
    displayName: Supported By
    type: string
    default: DORIS App Dev
  - name: ManagedBy
    displayName: Managed By
    type: string
    default: DORIS App Dev

resources:
  repositories:
  - repository: templates
    type: git
    name: cs-terraform/pipeline-templates
    ref: refs/tags/0.0.1

# CI Triggers
trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include: 
      - terraform/azure/*

pool: $(pool)

stages:
- stage: Create_tfvars
  jobs:
    - job:
      steps:
      - task: Bash@3
        displayName: 'Create tfvars file'
        inputs:
          targetType: 'inline'
          script: |
            cat << EOF > $(tf_directory)/terraform.tfvars
            tags = {
              Agency             = "${{ parameters.Agency }}"
              Environment        = "${{ parameters.Environment }}"
              Application        = "${{ parameters.Application }}"
              CreatedBy          = "Terraform"
              Project            = "${{ parameters.Project }}"
              UsedBy             = "${{ parameters.UsedBy }}"
              SupportedBy        = "${{ parameters.SupportedBy }}"
              ManagedBy          = "${{ parameters.ManagedBy }}"
            }
            EOF
            cat $(tf_directory)/terraform.tfvars
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: $(tf_directory)/terraform.tfvars
          artifactName: terraform_parameter_vars
- template: terraform-preflight-check.yaml@templates
- template: terraform-plan.yaml@templates
- template: terraform-apply.yaml@templates
